# Generated by Django 2.2.7 on 2019-11-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('course_number', models.IntegerField()),
                ('group_number', models.IntegerField()),
                ('teacher', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('first_day', models.CharField(choices=[('0', 'شنبه'), ('1', 'یک شنبه'), ('2', 'دو شنبه'), ('3', 'سه شنبه'), ('4', 'چهار شنبه')], max_length=1)),
                ('second_day', models.CharField(blank=True, choices=[('0', 'شنبه'), ('1', 'یک شنبه'), ('2', 'دو شنبه'), ('3', 'سه شنبه'), ('4', 'چهار شنبه')], max_length=1, null=True)),
            ],
        ),
    ]
