# Generated by Django 2.2.7 on 2019-11-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Course',
        ),
    ]
