# Generated by Django 2.2.7 on 2019-11-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20191108_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='course',
            name='first_day',
            field=models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='course',
            name='second_day',
            field=models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(max_length=120),
        ),
    ]
