# Generated by Django 2.2.7 on 2019-11-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_course_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exam_date',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
